#MBPP配置文件
#Design By MossCG
#基于腾讯云CVM的代理池管理系统

#前言
#当你确认配置没问题后，请将以下选项修改为true后再启动喵
enable: false

#----------------------------------
#HttpAPI模块信息

#HttpAPI端口
#token请务必修改，这是访问接口的最基础校验
httpPort: 7891
httpToken: "123456789abc"

#----------------------------------
#代理模块信息
#配置到代理服务器的代理账号
proxyAccount: "mosscg"
proxyPassword: "password2233"

#备用代理，建议设置为付费代理池，作为兜底
#此项开启时，当某session所有IP都用过了之后，会自动切换到备用代理
#否则会从用过的里面随机一个
enableBackup: false
backupHost: "xxx.xx.xx.xx"
backupPort: "12345"
backupUser: "abc"
backupPassword: "123"

#----------------------------------
#腾讯云模块信息

#基于腾讯云CVM
#腾讯云API密钥信息 (https://console.cloud.tencent.com/cam/capi)
TencentSecretId: "AKIDxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
TencentSecretKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

#IP池IP数量（必须大于等于1）
IPAmount: 2

#实例配置
#地域名称（如：ap-guangzhou、ap-beijing、ap-shanghai等）
regionName: "ap-guangzhou"
#可用区ID（如：ap-guangzhou-1、ap-beijing-1等）
zoneId: "ap-guangzhou-1"
#实例规格（建议选最小规格，够用了）：S5.SMALL1、S5.MEDIUM2等
instanceType: "S5.SMALL1"

#竞价实例配置
#是否启用竞价实例（Spot Instance）
enableSpotInstance: true
#竞价实例最高出价（单位：元/小时）
#设置为0表示接受市场价（自动设置为10元/小时限制）
#建议设置具体值，如: 0.5 表示最高愿意支付0.5元/小时
spotMaxPrice: 0.0
#当spotMaxPrice为0时的默认最高限制价格（元/小时）
spotDefaultMaxPrice: 1.0

#网络配置
#VPC网络ID（必须已存在）
vpcId: "vpc-xxxxxxxxx"
#子网ID（必须已存在）
subnetId: "subnet-xxxxxxxxx"
#安全组ID列表（必须已存在，建议开放全部端口）
securityGroupIds: ["sg-xxxxxxxxx"]

#实例统一账号密码（请务必修改）
CVMUser: "root"
CVMAuth: "123456abc"

#CVM存活时间上限（秒）
#配置时间需要一分钟左右，此项建议设置大于180
liveTime: 3600

#session超时时间（秒）
#超过该时间，同一session就可以复用该IP
#B站412风控应设为20min（1200s）
sessionTime: 1200

#----------------------------------
#MySQL数据库设置（暂时无用）

#MySQL基础设置
MySQLAddress: "127.0.0.1"
MySQLPort: "3306"
MySQLDatabase: "mbpp"
MySQLUser: "root"
MySQLPassword: "123456"

#----------------------------------
#是否显示调试信息
debug: true
